version: '3.8'
services: # apps containers you want to build and run
  vijayapp1: # name of appliction for compose
    image: vijaydotnetimg:v1  # image i want to build
    build: .  # path of dockerfile location -- . means current
    container_name: vijayc1 # it will create container also
    ports:
    - 9091:5000  # you guys can use port between 1024 to 60000
  vijayapp2: # creating httpd image and container 1
    image: vijayhttpd:version1
    build:
      context: .
      dockerfile: vijayhttpd.dockerfile
    container_name: vijayc2
    ports:
    - 1237:80  # you guys can use port between 1024 to 60000
    depends_on:
    - vijayapp1
